/* HIG 验收（在目标浏览器里量 DOM）。页面地址加 ?accept 即加载（再加 &quiet 不画覆盖层，只 POST）：把关键控件的实测尺寸和 DESIGN-HIG.md 的数字表比，
   左上角盖一块结果，并 POST 到本地 rangeserver 的 /accept（pipeline/ui/accept.py 收集）。
   只在 Safari/iOS 上的数字才算数：桌面 Chromium 没有 -apple-system-body，根字号是 16 而不是 17。 */
(function(){
  if(!/[?&]accept/.test(location.search)) return;
  const R=[]; const num=v=>Math.round(v*100)/100;
  const ok=(name, got, want, tol, note)=>{ const pass = typeof want==='number' ? Math.abs(got-want)<=tol : got===want; R.push({name, got: typeof got==='number'?num(got):got, want, pass, note}); };
  const clipInfo=el=>{ const m=/inset\(([^)]*?)\s*(?:round\s+([^)]*))?\)/.exec(el.style.clipPath||''); if(!m) return null; const ex=(str,n)=>{ const a=(str||'').trim().split(/\s+/).map(parseFloat); while(a.length<n) a.push(a.length>=2?a[a.length-2]:a[0]); return a; }; const ins=ex(m[1],4), rad=ex(m[2]||'0',4); return {cut:ins[2], rt:rad[0], rb:rad[2]}; };   // 浏览器会把相同值折叠（inset(0px 0px 399px round 34px)），按 CSS 简写规则展开
  const rect=el=>el.getBoundingClientRect(); const cs=(el,ps)=>getComputedStyle(el,ps||null); const px=v=>parseFloat(v)||0;
  const q=s=>document.querySelector(s); const qa=s=>[...document.querySelectorAll(s)].filter(e=>rect(e).width>0&&getComputedStyle(e).visibility!=='hidden');   /* 叠放卡片没打开时 visibility:hidden，不算 */
  const safeBottom=()=>{ const p=document.createElement('div'); p.style.cssText='position:fixed;top:0;left:0;width:0;height:0;padding-top:env(safe-area-inset-bottom)'; document.body.appendChild(p); const v=px(cs(p).paddingTop); p.remove(); return v; };
  const safeNow=()=>{ const p=document.createElement('div'); p.style.cssText='position:fixed;top:0;left:0;width:0;height:0;padding-top:env(safe-area-inset-top)'; document.body.appendChild(p); const v=px(cs(p).paddingTop); p.remove(); return v; };
  // 主屏幕网页 App（黑色半透明状态栏）里 innerHeight 不含状态栏、client 坐标整体偏 +安全区；用 visualViewport 校正：屏幕 y = client y + OY
  // 网页 App 冷启动后视口会在一两秒内从 894 变成 956（状态栏半透明生效），所以这些都在量的时候现算，不在脚本加载时算
  const VV=window.visualViewport; let W,H,OY,wide,MAC,safe,root,INSET;
  function run(){
    W=window.innerWidth; H=VV?VV.height:window.innerHeight; OY=0; /* 全站已不用 position:fixed，rect 就是屏幕坐标；visualViewport.offsetTop 在网页 App 里是 -安全区，只影响 fixed 元素 */ wide=W>=900; MAC=wide&&matchMedia('(pointer: fine)').matches; safe=safeNow(); root=px(cs(document.documentElement).fontSize); INSET=W>=414?20:16;
    R.length=0;
    ok(MAC?'根字号 = 13（macOS 27 UI Kit Body）':'根字号 = 17（-apple-system-body）', root, MAC?13:17, 0.01, 'Chromium 手机模式会是 16');
    const fam=cs(document.body).fontFamily; ok('字体栈含 PingFang SC', /PingFang SC/.test(fam), true, 0, fam.split(',').slice(0,4).join(','));
    const tint=cs(document.documentElement).getPropertyValue('--tint').trim(); ok('tint', tint.toLowerCase(), matchMedia('(prefers-color-scheme: dark)').matches?'#0a84ff':'#0088ff', 0);
    // 顶部工具条：44 圆钮，左 16，贴安全区顶
    const bar=q('.bar'); if(bar){ const b=qa('.bar .btn-glass')[0]; if(b){ const r=rect(b); const h48=!MAC&&!!bar.querySelector('.seg'); ok(MAC?'工具条按钮高 36':(h48?'工具条圆钮 48（Kit 48pt 变体，条里有 Large 分段）':'工具条按钮高 44'), r.height, MAC?36:(h48?48:44), 0.5); ok(MAC?'工具条按钮宽 ≥36':(h48?'工具条圆钮宽 ≥48':'工具条按钮宽 ≥44'), r.width>=(MAC?35.5:(h48?47.5:43.5)), true, 0, num(r.width)); if(wide){ const rb=Math.max(...qa('.bar > *').filter(b=>!b.classList.contains('spacer')).map(b=>rect(b).right)); ok(MAC?'工具条靠右 8（macOS 地图 App 控件簇）':'工具条靠右 24（iPad 地图 App 控件簇）', W-rb, MAC?8:24, 0.5); ok('工具条顶 = 安全区 + 8', Math.min(...qa('.bar .btn-glass').map(b=>rect(b).top)), safe+8, 0.5); ok(MAC?'工具条圆钮 36':'工具条圆钮 44', r.height, MAC?36:44, 0.5); } else { ok('工具条左内缩 = 布局边距 '+INSET, r.left, INSET, 0.5); ok('工具条按钮顶 = 安全区', r.top+OY, safe, 0.5, 'safe-top '+num(safe)); } } }
    // Sheet
    const sh=q('.sheet'); if(sh){ const r=rect(sh); const d=sh.dataset.detent||'medium'; const vis=Math.min(r.height, H-r.top);   /* ui/sheet.js 用 transform 定位，元素本身永远是大档高 */
      if(!wide){ if(d!=='large'){ ok('Sheet 左内缩 8', r.left, 8, 0.5); ok('Sheet 右内缩 8', W-r.right, 8, 0.5); const cp=clipInfo(sh); ok('Sheet 底内缩 8（Kit Medium Detent 浮起；clip-path 裁出）', cp?H-(r.bottom-cp.cut):NaN, 8, 0.5, sh.style.clipPath); ok('Sheet 四角 34（Kit 中档/Inspector）', cp&&Math.abs(cp.rt-34)<0.5&&Math.abs(cp.rb-34)<0.5, true, 0, sh.style.clipPath); } else { ok('Sheet 大档满宽贴底', r.left===0&&W-r.right===0&&!sh.style.clipPath, true, 0, num(r.left)+'/'+num(W-r.right)+' clip:'+sh.style.clipPath); ok('Sheet 大档上角 38（Kit Large Detent）', px(cs(sh).borderTopLeftRadius), 38, 0.5, cs(sh).borderRadius); }
        if(d==='medium') ok('Sheet 中档 = 44.2% 屏（422.67/956）', 100*vis/H, 44.21, 0.6); else if(d==='large') ok('Sheet 大档 = 屏高 − 62', H-vis, 62, 1); else ok('Sheet 小档 = 96 + 安全区底', vis, 96+safeBottom(), 1, '档位 small');
        const g=q('.sheet .grab i'); if(g){ const gr=rect(g); ok('抓手 60×4（Kit Top - Sheet）', gr.width===60&&Math.abs(gr.height-4)<0.5, true, 0, num(gr.width)+'×'+num(gr.height)); ok('抓手距顶 5', gr.top-r.top, 5, 0.5); ok('抓手居中', Math.abs((gr.left+gr.right)/2-(r.left+r.right)/2), 0, 1); }
      } else if(MAC){ // macOS 27 UI Kit（NUMBERS.md「macOS 27 UI Kit」）：侧栏 = Windows › Left Pane 256、内边 8、窗口圆角 16；地点面板 = Utility Panel 280
        const panel=sh.classList.contains('panel-wide'); ok(panel?'面板宽 280（Kit Utility Panel）':'侧栏宽 256（Kit Windows › Left Pane）', r.width, panel?280:256, 0.5); ok('侧栏左 8（Kit 面板内边）', r.left, 8, 0.5); ok('侧栏顶 8', r.top, safe+8, 0.5); ok('侧栏底 8', H-r.bottom, 8, 0.5); ok('侧栏圆角 16（Kit 窗口圆角）', px(cs(sh).borderTopLeftRadius), 16, 0.5);
        ok('根字号 13（Kit Body）', root, 13, 0.1);
        const cp=q('.sheet.split #card'); if(cp&&!cp.hidden){ const cr=rect(cp); ok('地点面板 280 宽、贴侧栏右 8', Math.abs(cr.width-280)<0.5&&Math.abs(cr.left-r.right-8)<0.5, true, 0, num(cr.width)+' left+'+num(cr.left-r.right)); ok('地点面板圆角 16', px(cs(cp).borderTopLeftRadius), 16, 0.5); const sn=qa('#card .stat .n'); sn.forEach((n,i)=>ok('统计卡数字不截断 #'+i, n.scrollWidth<=n.clientWidth+1, true, 0, n.textContent.trim())); const st=qa('#card .stat')[0]; if(st){ ok('统计卡圆角 12（Kit Group Box）', px(cs(st).borderTopLeftRadius), 12, 0.5); const sn0=st.querySelector('.n'); if(sn0) ok('统计卡数字 22（Kit Title 1）', px(cs(sn0).fontSize), 22, 0.2); } }
        const mr=qa('.sheet .mrow').find(x=>x.querySelector('.hint')); if(mr){ ok('侧栏行 40（Kit Sidebar Large）', rect(mr).height, 40, 0.5, mr.textContent.trim().slice(0,10)); const ic=mr.querySelector('.ico'); if(ic){ ok('侧栏行图标 24 距边 14', rect(ic).width===24&&Math.abs(rect(ic).left-r.left-14)<0.5, true, 0, num(rect(ic).width)+' @'+num(rect(ic).left-r.left)); } const nm=mr.querySelector('.name'); if(nm) ok('侧栏行标题 13 常规（Kit Regular 13）', Math.abs(px(cs(nm).fontSize)-13)<0.1&&+cs(nm).fontWeight<600, true, 0, cs(nm).fontSize+' w'+cs(nm).fontWeight); const ht=mr.querySelector('.hint'); if(ht) ok('侧栏行副标题 11（Kit Subheadline）', px(cs(ht).fontSize), 11, 0.2); ok('侧栏行圆角 8（Kit 选中底）', px(cs(mr).borderTopLeftRadius), 8, 0.5); }
        const mh=qa('.sheet .mh')[0]; if(mh){ const c=cs(mh); ok('侧栏段头 Bold 11（Kit Header）', Math.abs(px(c.fontSize)-11)<0.1&&+c.fontWeight>=700, true, 0, c.fontSize+' w'+c.fontWeight); ok('侧栏段头距边 14（Kit 内容内缩）', px(c.paddingLeft), 14, 0.1); }
      } else { ok('侧栏宽 440（iPad 地图 App）', r.width, 440, 0.5); ok('侧栏左 24', r.left, 24, 0.5); ok('侧栏顶 = 安全区 + 8', r.top, safe+8, 0.5); ok('侧栏底 20', H-r.bottom, 20, 0.5); ok('侧栏圆角 38', px(cs(sh).borderTopLeftRadius), 38, 0.5); }
      const s=qa('.sheet .search')[0]; if(s){ const sr=rect(s); ok(MAC?'搜索框高 36':'搜索胶囊高 44', sr.height, MAC?36:44, 0.5); ok(MAC?'搜索框距面板边 8（Kit 工具条内缩）':'搜索胶囊距 Sheet 内边 16', sr.left-r.left, MAC?8:16, 0.5); ok(MAC?'搜索框距面板顶 8（Kit 工具条距顶）':(wide?'搜索胶囊距面板顶 16':'搜索胶囊距 Sheet 顶 15'), sr.top-r.top, MAC?8:(wide?16:15), 0.5); if(MAC) ok('搜索框左内边 8（Kit 图标槽 @8）', px(cs(s).paddingLeft), 8, 0.1); else ok('搜索胶囊左内边 11', px(cs(s).paddingLeft), 11, 0.1); }
      const head=qa('.sheet .head')[0]; if(head&&!MAC){ const hb=qa('.sheet .head .btn-glass')[0]; if(hb){ const br=rect(hb); ok('卡片头圆钮 44', br.width===44&&br.height===44, true, 0, num(br.width)+'×'+num(br.height)); ok('卡片头圆钮距 Sheet 顶 16（Kit Top - Sheet）', br.top-r.top, 16, 0.5); ok('卡片头圆钮距 Sheet 边 16（Kit）', Math.min(br.left-r.left, r.right-br.right), 16, 0.5); const tt=head.querySelector('.tt .t-title2'); if(tt){ const tc=cs(tt); ok('卡片头标题 Semibold 15（Kit Title 2 Line）', Math.abs(px(tc.fontSize)-root*15/17)<0.2&&+tc.fontWeight>=600, true, 0, tc.fontSize+' w'+tc.fontWeight); ok('卡片头标题块距 Sheet 顶 21（Kit 19 + 2）', rect(tt).top-r.top, 21, 0.6); } }
        const tt=qa('.sheet .head .tt .t-title2')[0]; if(tt){ const c=cs(tt); ok('卡片头标题 Semibold 15/20（Kit Top - Sheet › Title 2 Line）', Math.abs(px(c.fontSize)-root*15/17)<0.2&&Math.abs(px(c.lineHeight)-root*20/17)<0.2&&+c.fontWeight>=600, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))+' w'+c.fontWeight); ok('卡片头标题居中', c.textAlign, 'center', 0); ok(wide?'卡片头标题距面板顶 16':'卡片头标题距 Sheet 顶 21（Kit：抓手块 15 + 1 + 5）', rect(tt).top-r.top, wide?16:21, 0.5); }
        const st=qa('.sheet .head .tt .t-sub')[0]; if(st){ const c=cs(st); ok('卡片头副标题 Medium 12/16（Kit）', Math.abs(px(c.fontSize)-root*12/17)<0.2&&+c.fontWeight>=500, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))+' w'+c.fontWeight); ok('卡片头副标题单行 16', rect(st).height, root*16/17, 0.5); }
        const body=qa('.sheet .body')[0]; if(body&&tt){ ok('正文距头内容底 10（Kit 头高 70 = 抓手块 15 + 1 + 44 + 10）', rect(body).top-rect(head).bottom+px(cs(head).paddingBottom), 10, 0.5); } }
    }
    // Sheet 物理（ui/sheet.js）：公式对 WWDC18 803 / WWDC23 10158 的数，合成手势对实测（NUMBERS.md「Sheet 物理」）
    if(sh&&!wide&&window.SHEET&&SHEET.sim){ const P=SHEET.physics, T=SHEET.tops(), cur0=SHEET.get();
      ok('投影 1000pt/s → 155pt（k 0.155s，地图 App 甩手实测）', P.project(1000), 155, 0.01);
      ok('橡皮筋 200pt（视口 '+num(H)+'）→ '+num((1-1/(200*.55/H+1))*H), P.rubber(200,H), (1-1/(200*.55/H+1))*H, 0.01);
      const sp=P.spring(100,0,0.34); ok('落档弹簧 duration .34 bounce 0：0.34s 后剩 1.36%', 100*sp[0]/100, 1.36, 0.05);
      ok('落档弹簧无过冲（临界阻尼）', P.spring(100,0,0.6)[0]>0&&P.spring(100,0,1.0)[0]>=0, true, 0);
      const fl=P.settleFor(-1250); let mn=0; for(let t=0;t<0.6;t+=0.005) mn=Math.min(mn, P.spring(411,-1250,t,fl)[0]); ok('甩手落档 bounce 0.2：411pt 过冲 5–9pt（地图 App 6.7）', -mn, 7, 2.5, 'bounce '+fl.bounce.toFixed(2));
      if(T.medium&&T.large){ const S=SHEET.sim, y0=600, t0=performance.now();
        S.place(T.medium); S.begin(y0,t0,false,false); S.move(y0-120,t0+80); ok('拖动跟手 1:1（上推 120）', SHEET.top(), T.medium-120, 0.01); S.move(y0-120,t0+300);
        ok('静止松手：离得近的档（中档 −120 → 回中档）', S.end(t0+300), 'medium', 0);
        const MAPS={large:62, medium:533.33};   // 地图 App 的档位（956 高屏）：甩手实验的判定按它的几何
        ok('甩手 60pt@1250pt/s → 大档（地图 App 实测）', P.nearest(MAPS, MAPS.medium-60+P.project(-1250)), 'large', 0);
        ok('甩手 60pt@1000pt/s → 留中档（地图 App 实测）', P.nearest(MAPS, MAPS.medium-60+P.project(-1000)), 'medium', 0);
        ok('甩手 30pt@1250pt/s → 留中档（地图 App 实测）', P.nearest(MAPS, MAPS.medium-30+P.project(-1250)), 'medium', 0);
        ok('甩手 50pt@1250pt/s → 大档（地图 App 实测）', P.nearest(MAPS, MAPS.medium-50+P.project(-1250)), 'large', 0);
        S.place(T.medium); S.begin(y0,t0,false,false); S.move(y0-30,t0+24); S.move(y0-60,t0+48); ok('合成甩手 60pt@1250：速度→投影→落档 = '+P.nearest(T, T.medium-60+P.project(-1250)), S.end(t0+48), P.nearest(T, T.medium-60+P.project(-1250)), 0);
        S.place(T.large); S.begin(y0,t0,false,false); S.move(y0-200,t0+100); ok('越过大档：橡皮筋（推 200 只走 '+num(P.rubber(200,H))+'）', T.large-SHEET.top(), P.rubber(200,H), 0.05); S.move(y0,t0+400); S.end(t0+400);
        S.place(T[cur0]); SHEET.set(cur0);
        const tr=window.__sheetTrace; if(tr&&tr.length>5){ const rel=tr.find(x=>x.phase==='settle'); const d0=rel?rel.top-rel.target:0; let worst=0, t1=null;
          let gap=0, pt=null; for(const x of tr){ if(x.phase!=='settle') continue; const m=x.target+P.spring(d0,0,Math.max(0,x.ta))[0]; if(x.ta>0) worst=Math.max(worst, Math.abs(x.top-m)); if(t1==null&&Math.abs(x.top-x.target)<1) t1=x.t; if(pt!=null) gap=Math.max(gap, x.t-pt); pt=x.t; }
          ok('真机落档轨迹 vs 弹簧模型（最大偏差 pt）', worst, 0, 1, 'd0 '+num(d0)+' 样本 '+tr.filter(x=>x.phase==='settle').length);
          ok('落档期间不掉帧（最长帧间隔 ≤ 34ms）', Math.round(gap*1000), 0, 34, '样本 '+tr.length);
          ok('真机落档 1pt 内用时 ≈ 0.37s（120pt，模型）', t1==null?9:t1, 0.37, 0.06); ok('真机落档终点 = 档位', tr[tr.length-1].top, tr[tr.length-1].target, 0.05); }
        else ok('真机落档轨迹已采到', !!tr, true, 0, '要在 load 后 600ms 由 accept.js 自己合成一次手势');
      } }
    // 行按下高亮（ui/press.js，地图 App 实测：触到即变、0.2s ease-out、systemGray4 85%、松手 0.1s 淡出、滚动即取消）
    if(window.HIGPress&&'ontouchstart' in window){ const P=window.HIGPress; ok('行高亮样式：systemGray4 85% / 0.2s ease-out / 淡出 0.1s', /rgba\(209,209,214,\.85\)/.test(P.CSS)&&/\.2s ease-out/.test(P.CSS)&&/\.1s ease-out/.test(P.CSS), true, 0);
      const lab=document.createElement('div'); lab.style.cssText='position:fixed;left:-9999px;top:0;width:300px'; lab.innerHTML='<div class="group"><a class="row" href="#"><span class="lab"><span class="name">探针行</span></span></a></div>'; document.body.appendChild(lab); const rw=lab.querySelector('.row');
      ok('行不可选字（长按不弹选择）', cs(rw).webkitUserSelect||cs(rw).userSelect, 'none', 0);
      const te=(type,x,y)=>{ const t=new Touch({identifier:1,target:rw,clientX:x,clientY:y}); window.__accSynthetic=true; try{ rw.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[t],changedTouches:[t]})); } finally { window.__accSynthetic=false; } };
      te('touchstart',10,10); ok('触到即高亮（同一帧加 class）', rw.classList.contains('hig-press'), true, 0); ok('高亮过渡 0.2s', cs(rw).transitionDuration, '0.2s', 0);
      te('touchmove',10,40); ok('滑动 >10pt 取消高亮', rw.classList.contains('hig-press'), false, 0);
      te('touchstart',10,10); te('touchend',10,10); ok('松手后高亮先留着（≥120ms 再淡出）', rw.classList.contains('hig-press'), true, 0); lab.remove();
      // 玻璃圆钮按下：×1.135、Spring(0.24, 0.4) 采样成 linear()（地图 App 右上圆钮实测）、亮度 1.3
      if(window.HIGSheet&&P.BTN_STOPS){ const S=HIGSheet.physics.spring; const pts=P.BTN_STOPS.replace(/linear\(|\)/g,'').split(',').map(Number); let worst=0; for(let i=0;i<pts.length;i++){ const t=0.36*i/(pts.length-1); const m=1+S(-1,0,t,{duration:.24,bounce:.4})[0]; worst=Math.max(worst, Math.abs(pts[i]-m)); }
        ok('圆钮按下曲线 = Spring(0.24, 0.4)（采样点最大偏差）', worst, 0, 0.01, pts.length+' 点'); ok('圆钮按下放大 1.135', P.BTN_SCALE, 1.135, 0.001);
        const lb=document.createElement('div'); lb.style.cssText='position:fixed;left:-9999px;top:0'; lb.innerHTML='<button class="btn-glass">x</button>'; document.body.appendChild(lb); const gb=lb.querySelector('.btn-glass');
        const tb=(type)=>{ const t=new Touch({identifier:2,target:gb,clientX:5,clientY:5}); window.__accSynthetic=true; try{ gb.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[t],changedTouches:[t]})); } finally { window.__accSynthetic=false; } };
        tb('touchstart'); ok('圆钮触到即变亮（brightness 1.3）', gb.classList.contains('hig-btn-press')&&/brightness\(1\.3\)/.test(cs(gb).filter), true, 0, cs(gb).filter); ok('圆钮触到即起放大动画', gb.getAnimations().length>0&&gb.getAnimations()[0].effect.getTiming().duration===P.BTN_MS, true, 0);
        tb('touchend'); ok('圆钮松手回 1', !gb.classList.contains('hig-btn-press'), true, 0); lb.remove(); } }
    // Sheet 的 .body 必须是滚动容器：大档时 .body 底边不超出 Sheet，内容长于视口就能滚（09-15 薪资页 #list 套一层把它撑没了，列表滚不动）
    if(window.SHEET&&SHEET.sim&&!wide){ const se=SHEET.el, sb=se.querySelector('.body'); if(sb){ const was=SHEET.get(), T=SHEET.tops(); const cls=se.className; se.classList.remove('small'); se.classList.add('large'); SHEET.sim.place(T.large);   // 按大档的 class 量（小档时页面可以 overflow:hidden）
      const sr=rect(se), br=rect(sb); ok('Sheet 大档：.body 底边不超出 Sheet', Math.round(br.bottom-sr.bottom), 0, 1, num(br.bottom)+' vs '+num(sr.bottom));
      ok('Sheet .body 允许原生竖向滚动（touch-action pan-y/auto，不能继承 .sheet 的 none）', ['pan-y','auto','manipulation'].includes(cs(sb).touchAction), true, 0, cs(sb).touchAction);
      ok('Sheet .body 是滚动容器（overflow auto，内容长就能滚）', cs(sb).overflowY==='auto'&&(sb.scrollHeight<=sb.clientHeight+1||sb.clientHeight<sb.scrollHeight), true, 0, 'clientH '+num(sb.clientHeight)+' scrollH '+num(sb.scrollHeight));
      se.className=cls; SHEET.sim.place(T[was]??T.medium); } }
    // 叠放卡片（HIGSheet.stack：地图 App 地点卡片 = 第二张 Sheet 从底下弹上来，后面那张退到中档）
    if(window.CARD&&!wide&&window.SHEET){ const C=window.CARD; const wasShown=C.shown; if(!wasShown) C.present(); const ce=C.ctl.el; const T=C.ctl.tops();
      ok('叠放卡片挂在 body 下、带 .sheet.stacked', ce.parentNode===document.body&&ce.classList.contains('stacked'), true, 0);
      ok('叠放卡片：present 后落中档', C.ctl.get(), 'medium', 0); ok('叠放卡片从视口底边起飞（top = H）', C.ctl.top(), C.ctl.sim.H(), 1.5);
      C.ctl.sim.place(T.medium); const cr=rect(ce); { const cp2=clipInfo(ce); ok('叠放卡片四角 34、左右底内缩 8（Kit 中档）', cp2&&Math.abs(cp2.rt-34)<0.5&&Math.abs(cp2.rb-34)<0.5&&Math.abs(cr.left-8)<0.5&&Math.abs(H-(cr.bottom-cp2.cut)-8)<0.5, true, 0, ce.style.clipPath+' left '+num(cr.left)); }
      const cg=ce.querySelector('.grab i'); if(cg) ok('叠放卡片抓手 60×4 距顶 5', Math.abs(rect(cg).width-60)<0.5&&Math.abs(rect(cg).top-cr.top-5)<0.5, true, 0, num(rect(cg).width)+' @'+num(rect(cg).top-cr.top));
      const cb=ce.querySelector('.head .btn-glass'); if(cb) ok('叠放卡片关闭钮 44 距顶 16 距边 16（Kit）', Math.abs(rect(cb).height-44)<0.5&&Math.abs(rect(cb).top-cr.top-16)<0.5&&Math.abs(cr.right-rect(cb).right-16)<0.5, true, 0, num(rect(cb).top-cr.top)+'/'+num(cr.right-rect(cb).right));
      if(!wasShown){ C.dismiss(); ok('叠放卡片：dismiss 后 shown=false', C.shown, false, 0); } }
    // 功能探针（09-15 审查修的 bug，各页自己的）
    if(location.pathname.includes('/osaka/')&&typeof dropPin==='function'&&window.map){ const n0=document.querySelectorAll('.maplibregl-marker').length; try{ dropPin({lng:135.50,lat:34.70}); dropPin({lng:135.51,lat:34.71}); }catch(e){}
      ok('落两次钉子后钉子还在（#22）', document.querySelectorAll('.maplibregl-marker').length-n0, 1, 0); const pp=document.querySelector('.maplibregl-popup'); ok('钉子气泡带来源等级（#27）', !!pp&&/实测|锚定|借用/.test(pp.innerText), true, 0);
      ok('低频开关叫法统一「⚡ 低频线」（#34）', /⚡ 低频线/.test(document.getElementById('lowfreq').closest('label').innerText), true, 0);
      ok('图例行不是按钮（#38）', [...document.querySelectorAll('#lg .mrow')].every(r=>r.classList.contains('no-press')), true, 0);
      ok('面覆盖画布在标记之下（#24）', (()=>{ const a=document.querySelector('canvas.area'); if(!a) return true; const kids=[...window.map.getCanvasContainer().children]; const mi=kids.findIndex(k=>k.classList&&k.classList.contains('maplibregl-marker')); return kids.indexOf(a)>=0&&(mi<0||kids.indexOf(a)<mi); })(), true, 0);
      if(window.pin){ try{ pin.remove(); window.pin=null; }catch(e){} } const pp2=document.querySelector('.maplibregl-popup'); if(pp2) pp2.remove(); }
    if(location.pathname.includes('/japan/')&&window.map&&typeof onMapClick==='function'){ try{ onMapClick({point:window.map.project([150.0,30.0])}); }catch(e){}
      ok('点空白后卡片、关闭钮、卡片容器一起收（#44）', document.getElementById('card').style.display==='none'&&document.getElementById('cardSect').hidden&&document.getElementById('cClose').hidden, true, 0);
      ok('点空白后所有选中描边清空（#43）', ['jp-selk','ea-sub-sel','ea-rus-sel','jp-disp-sel'].every(id=>!window.map.getLayer(id)||JSON.stringify(window.map.getFilter(id)).includes('\\u0000')), true, 0);
      ok('区高亮按 市+区 过滤、只在 z≥8 画（#40）', window.map.getLayer('jp-selk')&&window.map.getLayer('jp-selk').minzoom>=8, true, 0);
      ok('東亜卡片有国家名对照表（#45）', typeof CN_NAME==='object'&&Object.keys(CN_NAME).length>=20, true, 0);
      ok('海域・远岛层在（EEZ 线 + 岛体 + 岛名，默认开，#54）', ['jp-eez','jp-isl-fill','jp-isl-lab'].every(id=>window.map.getLayer(id))&&document.getElementById('b-sea')&&document.getElementById('b-sea').checked, true, 0);
      ok('東亜争议区有隐形命中层（#42）', !!window.map.getLayer('ea-disp-fill'), true, 0);
      ok('地图没有样式/瓦片错误（window.__mapErr）', (window.__mapErr||[]).length, 0, 0, (window.__mapErr||[]).slice(0,2).join(' | ')); }
    if(location.pathname.includes('/quiz/')&&typeof setMode==='function'&&typeof updateLabels==='function'){ const info=document.getElementById('info'); ok('クイズ详情卡不被小档 Sheet 盖住（bottom = safe+144，#55）', px(cs(info).bottom)>=144, true, 0, cs(info).bottom);
      const sl=document.getElementById('showLabels'); const was=sl.checked; sl.checked=true; const vis=()=>[...document.querySelectorAll('svg text')].filter(t=>t.textContent&&cs(t).display!=='none').length; setMode('browse'); const b=vis(); setMode('quiz'); const q=vis();
      ok('答题时县名标签不显示（#61）', q<b/3, true, 0, b+' → '+q); ok('闯关/答题时「范围」行灰掉（#62）', (setMode('campaign'), document.getElementById('scope').closest('.r').classList.contains('disabled')), true, 0);
      setMode('browse'); sl.checked=was; updateLabels(); }
    // 分组列表（首页）：桌面 = Kit Group Box r12 内缩 14 + Sidebar Large 行 40 图标 24 + Header 18 / Bold 11
    if(MAC){ const g=qa('.group')[0]; if(g){ ok('分组 = Kit Group Box r12', px(cs(g).borderTopLeftRadius), 12, 0.5); ok('分组内缩 14', rect(g).left-(g.closest('main')?rect(g.closest('main')).left:0), 14, 0.5); const rw=qa('.group .row')[0]; if(rw){ ok('首页行 40（Kit Sidebar Large）', rect(rw).height, 40, 0.5); const ic=rw.querySelector('.ico'); if(ic) ok('首页行图标 24', rect(ic).width, 24, 0.5); ok('首页行无箭头', !qa('.group .row .chev').length, true, 0); } const h2=qa('.sect h2')[0]; if(h2){ const c=cs(h2); ok('首页段头 Bold 11 secondary', Math.abs(px(c.fontSize)-11)<0.1&&+c.fontWeight>=700, true, 0, c.fontSize+' w'+c.fontWeight); } } }
    else { const g=qa('.group')[0]; if(g){ ok('卡片圆角 26', px(cs(g).borderTopLeftRadius), 26, 0.5); const gr=rect(g); const host=sh&&sh.contains(g)?rect(sh):(g.closest('main')?rect(g.closest('main')):{left:0,right:W}); ok('卡片内缩 = 布局边距 '+INSET, gr.left-host.left, INSET, 0.5); }
    const single=qa('.row').find(r=>!r.querySelector('.hint,.seg,input[type=range]')&&!r.classList.contains('slider')); if(single){ const rr=rect(single); ok('单行 52.33（Row Regular 52 + 分隔线）', rr.height, 52.33, 0.5, single.textContent.trim().slice(0,12)); ok('行左内缩 '+(single.classList.contains('icon')?'18（有图标）':'20'), px(cs(single).paddingLeft), single.classList.contains('icon')?18:20, 0.1); ok('行右内缩 20', px(cs(single).paddingRight), 20, 0.1);
      const nx=single.nextElementSibling; if(nx&&nx.classList.contains('row')){ const sp=cs(nx,'::before'); ok('分隔线内缩 '+(nx.classList.contains('icon')?60:20), px(sp.left), nx.classList.contains('icon')?60:20, 0.1); ok('分隔线 0.67 粗', Math.abs(px(sp.height)*parseFloat((sp.transform.match(/matrix\(([^)]+)\)/)||['','1,0,0,1'])[1].split(',')[3])-0.67)<0.05, true, 0, sp.height+' '+sp.transform); } }
    const two=qa('.row').find(r=>r.querySelector('.hint')); if(two){ const rr=rect(two); ok('双行 68.33（Row Tall 68 + 分隔线）', rr.height, 68.33, 0.5, two.textContent.trim().slice(0,12)); }
    const ico=qa('.row .ico')[0]; if(ico){ const ir=rect(ico); const rw=rect(ico.closest('.row')); ok('行图标 28', ir.width===28&&ir.height===28, true, 0, num(ir.width)+'×'+num(ir.height)); ok('行图标距卡片边 18', ir.left-rw.left, 18, 0.1); ok('行文字起点 60', rect(ico.closest('.row').querySelector('.lab')).left-rw.left, 60, 0.5); }
    const nm=qa('.row .name')[0]; if(nm){ ok('行文字 17/22', px(cs(nm).fontSize)===root && Math.abs(px(cs(nm).lineHeight)-root*22/17)<0.3, true, 0, px(cs(nm).fontSize)+'/'+num(px(cs(nm).lineHeight))); }
    const h2=qa('.sect h2')[0]; if(h2){ const c=cs(h2); ok('段头 17 半粗', px(c.fontSize)===root&&+c.fontWeight>=600, true, 0, px(c.fontSize)+' w'+c.fontWeight); ok('段头下距 6', px(c.paddingBottom), 6, 0.1); const nxt=h2.nextElementSibling; if(nxt) ok('段头→卡片 6', rect(nxt).top-rect(h2).bottom, 0, 0.5, '内边距已含'); const sec=h2.parentElement; const isFirst=sec===sec.parentElement.firstElementChild; ok(isFirst?'首段头上距 10':'段头上距 28', px(c.paddingTop), isFirst?10:28, 0.1); const inSheet=!!(sh&&sh.contains(h2)); ok(inSheet?'段头内缩 = 布局边距（地图 App 卡片：与卡片对齐）':'段头文字内缩 = 布局边距 + 20（设置 App）', px(c.paddingLeft), inSheet?INSET:INSET+20, 0.1); ok('段头颜色 = '+(inSheet?'label（地图 App）':'secondaryLabel（设置 App）'), c.color, inSheet?cs(document.body).color:c.color, 0); }
    const ft=qa('.sect .foot').find(f=>f.previousElementSibling&&f.previousElementSibling.classList.contains('group')); if(ft){ const c=cs(ft); ok('段尾 13/18', Math.abs(px(c.fontSize)-root*13/17)<0.2&&Math.abs(px(c.lineHeight)-root*18/17)<0.3, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))); ok('段尾上 6 下 24', px(c.paddingTop)===6&&px(c.paddingBottom)===24, true, 0, c.paddingTop+' '+c.paddingBottom); }
    const gg=qa('.group + .group')[0]; if(gg){ ok('卡片间 35', px(cs(gg).marginTop), 35, 0.1); } }
    if(MAC){ // 桌面 = macOS 27 UI Kit（Sketch 套件）：开关 Regular 54×24、分段 Regular 24 r6、工具条分段 XL 36（段 28）、按钮 Regular 24 / XL 36
      const sw=qa('.sw')[0]; if(sw&&!document.documentElement.classList.contains('native-switch')){ const r=rect(sw); ok('开关 54×24（Kit Toggles › Regular）', r.width===54&&r.height===24, true, 0, num(r.width)+'×'+num(r.height)); const kn=cs(sw.querySelector('i'),'::after'); ok('开关圆钮 32×20', px(kn.width)===32&&px(kn.height)===20, true, 0, kn.width+'×'+kn.height); }
      const bseg=qa('.bar .seg')[0]; if(bseg){ ok('工具条分段控件 36（Kit XL）', rect(bseg).height, 36, 0.5); const b0=bseg.querySelector('button'); if(b0) ok('工具条分段段高 28（Kit XL 段 32×28）', rect(b0).height, 28, 0.5); }
      const sseg=qa('.sheet .seg')[0]; if(sseg){ ok('侧栏分段控件 24 r6（Kit Regular）', Math.abs(rect(sseg).height-24)<0.5&&Math.abs(px(cs(sseg).borderTopLeftRadius)-6)<0.5, true, 0, num(rect(sseg).height)+' r'+cs(sseg).borderTopLeftRadius); }
      const bl=qa('.btn.l')[0]; if(bl) ok('主按钮 36 胶囊（Kit XL）', rect(bl).height, 36, 0.5);
      const bs=qa('.btn.s')[0]; if(bs) ok('小按钮 24 r6（Kit Regular）', Math.abs(rect(bs).height-24)<0.5&&Math.abs(px(cs(bs).borderTopLeftRadius)-6)<0.5, true, 0, num(rect(bs).height)+' r'+cs(bs).borderTopLeftRadius);
      const chip=qa('.chips button')[0]; if(chip) ok('筛选胶囊 28（Kit Large 胶囊）', rect(chip).height, 28, 0.5);
      if(!document.documentElement.classList.contains('native-switch')){ // 开关 lab（Kit Regular：圆钮位移 20，按下 50×31 = scale 1.5625,1.55）
        const lab=document.createElement('div'); lab.style.cssText='position:fixed;left:-9999px;top:0';
        lab.innerHTML='<label class="sw"><input type="checkbox" checked><i></i></label><label class="sw"><input type="checkbox"><i></i></label>'; document.body.appendChild(lab);
        const [on]=lab.querySelectorAll('.sw i'); const kx=/matrix\([^)]*,\s*([-\d.]+),\s*[-\d.]+\)$/.exec(cs(on,'::after').transform); ok('开关开：圆钮位移 20（Kit Regular）', kx?parseFloat(kx[1]):NaN, 20, 0.5, cs(on,'::after').transform);
        const held=lab.querySelectorAll('.sw')[1]; held.classList.add('live','hold'); const hm=/matrix\(([-\d.]+),\s*[-\d.]+,\s*[-\d.]+,\s*([-\d.]+)/.exec(cs(held.querySelector('i'),'::after').transform);
        ok('按住：圆钮 50×31（scale 1.5625,1.55，Kit Clicked）', hm&&Math.abs(parseFloat(hm[1])-1.5625)<0.02&&Math.abs(parseFloat(hm[2])-1.55)<0.02, true, 0, cs(held.querySelector('i'),'::after').transform); held.classList.remove('hold');
        lab.remove(); }
    }
    if(!MAC){   // 地图 App 的 Sheet 内容组件（DESIGN-HIG.md「地图 App 组件」）——手机 / iPad；桌面走上面的 macOS 27 UI Kit 分支
    const mh=qa('.mh')[0]; if(mh){ const c=cs(mh); const host=sh&&sh.contains(mh)?rect(sh):{left:0}; ok('段头 17 半粗 secondaryLabel（Kit Lists › Header › Nested）', px(c.fontSize)===root&&+c.fontWeight>=600&&/60,\s*60,\s*67|235,\s*235,\s*245/.test(c.color), true, 0, px(c.fontSize)+' w'+c.fontWeight+' '+c.color); ok('地图段头距 Sheet 边 = 布局边距', px(c.paddingLeft), INSET, 0.1); ok('地图段头下距 10', px(c.paddingBottom), 10, 0.1); if(mh!==mh.parentElement.firstElementChild) ok('地图段头上距 28', px(c.paddingTop), 28, 0.1); }
    const mc=qa('.mcard')[0]; if(mc){ const r=rect(mc); const host=sh&&sh.contains(mc)?rect(sh):{left:0}; ok('地图卡片圆角 20', px(cs(mc).borderTopLeftRadius), 20, 0.5); ok('地图卡片距 Sheet 边 = 布局边距', r.left-host.left, INSET, 0.5); ok('地图卡片半透明填充', cs(mc).backgroundColor!=='rgba(0, 0, 0, 0)', true, 0, cs(mc).backgroundColor);
      const rr=qa('.mcard .r').find(x=>!x.querySelector('.hint,.seg,input[type=range],.chip')&&!x.classList.contains('slider')); if(rr){ ok('地图卡片行 47（17/22 + 12.5×2）', rect(rr).height, 47, 0.5, rr.textContent.trim().slice(0,10)); ok('地图卡片行左右内边 16', px(cs(rr).paddingLeft)===16&&px(cs(rr).paddingRight)===16, true, 0, cs(rr).padding); const nx=rr.nextElementSibling; if(nx&&nx.classList.contains('r')){ const sp=cs(nx,'::before'); ok('地图卡片分隔线 1 内缩 16', px(sp.height)===1&&px(sp.left)===16, true, 0, sp.height+' '+sp.left); } } }
    const ml=qa('.mlist')[0]; if(ml){ const r=rect(ml); const host=sh&&sh.contains(ml)?rect(sh):{left:0}; ok('地图列表卡片圆角 26', px(cs(ml).borderTopLeftRadius), 26, 0.5); ok('地图列表距 Sheet 边 = 布局边距', r.left-host.left, INSET, 0.5);
      const mr=qa('.mrow').find(x=>x.querySelector('.hint')); if(mr){ ok('列表行 68（Kit Rows › Large：14 + 17/22 + 15/18 + 14）', rect(mr).height, 68, 0.5, mr.textContent.trim().slice(0,10)); const ic=mr.querySelector('.ico'); if(ic){ const ir=rect(ic); ok('地图列表圆图标 34', ir.width===34&&ir.height===34, true, 0, num(ir.width)+'×'+num(ir.height)); ok('地图列表圆图标距卡片边 16', ir.left-rect(mr).left, 16, 0.1); ok('地图列表文字起点 61', rect(mr.querySelector('.lab')).left-rect(mr).left, 61, 0.5); } const nx=mr.nextElementSibling; if(nx&&nx.classList.contains('mrow')){ const sp=cs(nx,'::before'); ok('地图列表分隔线 1 内缩 61/16', px(sp.height)===1&&px(sp.left)===61&&px(sp.right)===16, true, 0, sp.height+' '+sp.left+' '+sp.right); } } }
    const ch=qa('.chips button')[0]; if(ch){ const inSheet=sh&&sh.contains(ch); ok('筛选胶囊 32', rect(ch).height, 32, 0.5); ok('筛选胶囊间距 8', px(cs(ch.parentElement).columnGap||cs(ch.parentElement).gap), 8, 0.1); const on=qa('.chips button[aria-pressed="true"]')[0]; if(on) ok('选中胶囊 tint 白字', cs(on).color==='rgb(255, 255, 255)', true, 0, cs(on).backgroundColor); }
    const tl2=qa('.tiles button')[0]; if(tl2){ const im=tl2.querySelector('.img'); ok('地图模式缩略块 91（87 + 2 描边）', rect(im).width===91&&rect(im).height===91, true, 0, num(rect(im).width)+'×'+num(rect(im).height)); ok('缩略块间距 10', px(cs(tl2.parentElement).columnGap||cs(tl2.parentElement).gap), 10, 0.1); const lb=tl2.querySelector('.lb'); ok('缩略块标签 13 距块 10', Math.abs(px(cs(lb).fontSize)-root*13/17)<0.2&&px(cs(lb).marginTop)===10, true, 0, num(px(cs(lb).fontSize))+' mt'+cs(lb).marginTop); }
    const sg=qa('.sugg')[0]; if(sg){ ok('建议卡圆角 16', px(cs(sg).borderTopLeftRadius), 16, 0.5); const ic=sg.querySelector('.ico'); if(ic) ok('建议卡圆图标 36', rect(ic).width, 36, 0.5); ok('建议卡标题 17 半粗', +cs(sg.querySelector('.t')).fontWeight>=600&&px(cs(sg.querySelector('.t')).fontSize)===root, true, 0); }
    const st=qa('.stat')[0]; if(st){ const sr=rect(st); const host=sh&&sh.contains(st)?rect(sh):{left:0,right:W}; ok('统计卡圆角 20 内边 16（健身 › 摘要）', px(cs(st).borderTopLeftRadius)===20&&px(cs(st).paddingLeft)===16, true, 0, cs(st).borderTopLeftRadius+' p'+cs(st).paddingLeft); ok('统计卡距 Sheet 边 20', sr.left-host.left, 20, 0.5); const g=st.parentElement; ok('统计卡两列间 10', px(cs(g).columnGap||cs(g).gap), 10, 0.1); const t=st.querySelector('.t'); if(t) ok('统计卡标题 17 半粗', px(cs(t).fontSize)===root&&+cs(t).fontWeight>=600, true, 0, px(cs(t).fontSize)+' w'+cs(t).fontWeight); const n=st.querySelector('.n'); if(n) ok('统计卡大数 28 粗', Math.abs(px(cs(n).fontSize)-root*28/17)<0.2&&+cs(n).fontWeight>=700, true, 0, num(px(cs(n).fontSize))+' w'+cs(n).fontWeight); const sb=st.querySelector('.s'); if(sb) ok('统计卡副标题 15 灰', Math.abs(px(cs(sb).fontSize)-root*15/17)<0.2, true, 0, num(px(cs(sb).fontSize))); }
    const ac=qa('.actions .btn'); if(ac.length){ const r0=rect(ac[0]); const host=sh&&sh.contains(ac[0])?rect(sh):{left:0,right:W}; ok('动作行按钮 50 高（地点卡片多按钮行）', r0.height, 50, 0.5); ok('动作行距 Sheet 边 20', r0.left-host.left, 20, 0.5); if(ac[1]) ok('动作行间距 8', rect(ac[1]).left-r0.right, 8, 0.5); ok('动作行等宽', Math.abs(rect(ac[ac.length-1]).width-r0.width)<1, true, 0, ac.map(b=>num(rect(b).width)).join('/')); ok('动作行首枚 tint 白字', cs(ac[0]).color==='rgb(255, 255, 255)', true, 0, cs(ac[0]).backgroundColor); const lb=ac[0].querySelector('span'); if(lb) ok('动作行标签 13 半粗', Math.abs(px(cs(lb).fontSize)-root*13/17)<0.2, true, 0, num(px(cs(lb).fontSize))); }
    const os=q('.sheet.opt'); if(os){ const was=os.hidden; os.hidden=false; const t=os.querySelector('.head .t-head'); if(t) ok('选项 Sheet 标题 17 半粗居中（地图模式）', px(cs(t).fontSize)===root&&+cs(t).fontWeight>=600&&cs(t.parentElement).textAlign==='center', true, 0); const cb=os.querySelector('.head .btn-glass'); if(cb) ok('选项 Sheet 关闭钮 44 距边 15', rect(cb).width===44&&Math.abs(rect(os).right-rect(cb).right-15)<0.5, true, 0, num(rect(os).right-rect(cb).right)); os.hidden=was; }
    const pb=qa('.mbtn .btn.l')[0]; if(pb){ const r=rect(pb); const host=sh&&sh.contains(pb)?rect(sh):{left:0,right:W}; ok('地图主按钮 50 高距 Sheet 边 20', Math.abs(r.height-50)<0.5&&Math.abs(r.left-host.left-20)<0.5, true, 0, num(r.height)+' left+'+num(r.left-host.left)); }
    // 控件
    const seg=qa('.seg').find(x=>!x.closest('.bar')); if(seg){ const c=cs(seg); ok('分段控件高 '+(seg.classList.contains('l')?50:32), rect(seg).height, seg.classList.contains('l')?50:32, 0.5); ok('分段内边 2 段间 4', px(c.paddingTop)===2&&px(c.columnGap||c.gap)===4, true, 0, c.padding+' gap '+(c.columnGap||c.gap)); const on=seg.querySelector('[aria-pressed="true"]'); if(on) ok('选中段白底', cs(on).backgroundColor!=='rgba(0, 0, 0, 0)', true, 0, cs(on).backgroundColor); }
    const bs={s:28,m:34,l:50}; for(const k in bs){ const b=qa('.btn.'+k)[0]; if(b) ok('按钮 '+k.toUpperCase()+' 高 '+bs[k], rect(b).height, bs[k], 0.5); }
    const bseg=qa('.bar .seg')[0]; if(bseg){ ok('工具条分段控件 48（Kit Segmented › Large）', rect(bseg).height, 48, 0.5); const b0=bseg.querySelector('button'); if(b0) ok('工具条分段段 44 内边 2', Math.abs(rect(b0).height-44)<0.5&&Math.abs(rect(b0).top-rect(bseg).top-2)<0.5, true, 0, num(rect(b0).height)+' @'+num(rect(b0).top-rect(bseg).top)); }
    const sw=qa('.sw')[0]; if(sw&&document.documentElement.classList.contains('native-switch')){ const r=rect(sw.querySelector('input')); ok('开关 = Safari 原生 switch（尺寸随系统）', r.width>20&&r.height>14, true, 0, num(r.width)+'×'+num(r.height)); }
    else if(sw){ const r=rect(sw); ok('开关 63×28', r.width===63&&r.height===28, true, 0, num(r.width)+'×'+num(r.height)); const k=cs(sw.querySelector('i'),'::after'); ok('开关圆钮 38×24', px(k.width)===38&&px(k.height)===24, true, 0, k.width+'×'+k.height); }
    // 开关动效探针（照 hig-kit/tools/accept-phone.js 的 lab 样本，不用录像）：屏外造两个开关量颜色、位移、镜片、轻点只翻一次
    if(!document.documentElement.classList.contains('native-switch')){
      const lab=document.createElement('div'); lab.style.cssText='position:fixed;left:-9999px;top:0';
      lab.innerHTML='<label class="sw"><input type="checkbox" checked><i></i></label><label class="sw"><input type="checkbox"><i></i></label>'; document.body.appendChild(lab);
      const dark=matchMedia('(prefers-color-scheme: dark)').matches; const [on,off]=lab.querySelectorAll('.sw i');
      ok('开关开 = 系统绿', cs(on).backgroundColor, dark?'rgb(48, 209, 88)':'rgb(52, 199, 89)', 0);
      ok('开关关 = 灰', /60,\s*60,\s*67|120,\s*120,\s*128/.test(cs(on.parentElement.nextElementSibling.querySelector('i')).backgroundColor), true, 0, cs(off).backgroundColor);
      const kx=/matrix\([^)]*,\s*([-\d.]+),\s*[-\d.]+\)$/.exec(cs(on,'::after').transform); ok('开关开：圆钮位移 21', kx?parseFloat(kx[1]):NaN, 21, 0.5);
      const held=lab.querySelectorAll('.sw')[1]; held.classList.add('live','hold'); const hm=/matrix\(([-\d.]+),\s*[-\d.]+,\s*[-\d.]+,\s*([-\d.]+)/.exec(cs(held.querySelector('i'),'::after').transform);
      ok('按住：圆钮放大成 58×38（scale 1.526,1.583）', hm&&Math.abs(parseFloat(hm[1])-1.526)<0.02&&Math.abs(parseFloat(hm[2])-1.583)<0.02, true, 0, hm?hm[1]+','+hm[2]:'none');
      ok('按住：圆钮变半透明玻璃', /gradient/.test(cs(held.querySelector('i'),'::after').backgroundImage), true, 0); held.classList.remove('hold');
      const tapSw=held, tapIn=tapSw.querySelector('input'); let changes=0; tapIn.addEventListener('change',()=>changes++); const was=tapIn.checked;
      const pe=(type,t)=>t.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:7,clientX:10,clientY:10,isPrimary:true}));
      pe('pointerdown',tapIn); pe('pointerup',tapSw); tapIn.click();
      ok('轻点一下：开关翻转一次', tapIn.checked===!was, true, 0, was+'→'+tapIn.checked); ok('轻点一下：change 只发一次', changes, 1, 0);
      lab.remove();
    }
    const sl=qa('.row.slider input[type=range]')[0]; if(sl) ok('滑块热区 28', rect(sl).height, 28, 0.5);
    }
    const mn=q('.menu'); if(mn&&MAC){ const was=mn.hidden; mn.hidden=false; const mb=mn.querySelector('button'); ok('菜单 = Kit Menus Regular：r12 内边 5/12', px(cs(mn).borderTopLeftRadius)===12&&px(cs(mn).paddingTop)===5&&px(cs(mn).paddingLeft)===12, true, 0, cs(mn).borderTopLeftRadius+' '+cs(mn).padding); if(mb) ok('菜单行 24 文字起点 31 r8', Math.abs(rect(mb).height-24)<0.5&&px(cs(mb).paddingLeft)===31&&px(cs(mb).borderTopLeftRadius)===8, true, 0, num(rect(mb).height)+' pl'+cs(mb).paddingLeft+' r'+cs(mb).borderTopLeftRadius); mn.hidden=was; }
    else if(mn){ const was=mn.hidden; mn.hidden=false; const mb=mn.querySelector('button'); ok('下拉菜单 248 宽 圆角 26（UIMenu）', Math.abs(rect(mn).width-248)<0.5&&px(cs(mn).borderTopLeftRadius)===26, true, 0, num(rect(mn).width)+' r'+cs(mn).borderTopLeftRadius); if(mb) ok('菜单行 42 标签距左 50', Math.abs(rect(mb).height-42)<0.5&&px(cs(mb).paddingLeft)===50, true, 0, num(rect(mb).height)+' pl'+cs(mb).paddingLeft); ok('菜单上下内边 5', px(cs(mn).paddingTop)===5&&px(cs(mn).paddingBottom)===5, true, 0, cs(mn).padding); mn.hidden=was; }
    const tl=qa('.t-large')[0]; if(tl){ const c=cs(tl); ok('大标题 34/41 700', Math.abs(px(c.fontSize)-root*2)<0.2&&+c.fontWeight>=700, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))+' w'+c.fontWeight); }
    const sfx=qa('.sf')[0]; if(sfx){ const m=cs(sfx).maskImage||cs(sfx).webkitMaskImage; ok('SF Symbols 蒙版已装', /ui\/sf\/.+\.png/.test(m), true, 0, (m||'').slice(0,60)); }
    const mv=cs(document.documentElement).getPropertyValue('--ease').trim(); if(matchMedia('(prefers-reduced-motion: reduce)').matches) ok('减弱动态：过渡关闭', cs(sh||document.body).transitionDuration, '0s', 0);
    // 深色
    const dark=matchMedia('(prefers-color-scheme: dark)').matches; ok('配色 = 系统'+(dark?'深':'浅')+'色', cs(document.body).backgroundColor, dark?'rgb(0, 0, 0)':(sh?cs(document.body).backgroundColor:'rgb(242, 242, 247)'), 0);
    return R;
  }
  function show(){
    const res=run(); const bad=res.filter(r=>!r.pass);
    if(!/[?&]quiet/.test(location.search)){
    let box=q('#accept'); if(!box){ box=document.createElement('pre'); box.id='accept'; box.style.cssText='position:fixed;top:0;left:0;z-index:9999;margin:0;max-height:100dvh;overflow:auto;font:11px/1.45 ui-monospace,Menlo,monospace;background:rgba(255,255,255,.94);color:#000;padding:calc(env(safe-area-inset-top) + 6px) 8px 8px;max-width:100%;white-space:pre-wrap'; document.body.appendChild(box); }
    box.textContent=`${location.pathname}  ${W}×${H}${navigator.standalone?' 网页App':''}  ${bad.length?'✗ '+bad.length+' 项超差':'✓ 全部通过'}  (${res.length} 项)\n`+res.map(r=>`${r.pass?'✓':'✗'} ${r.name}: ${r.got}${r.want!==undefined&&!r.pass?'  期望 '+r.want:''}${r.note?'  ['+r.note+']':''}`).join('\n');
    }
    document.title=(bad.length?'ACCEPT-FAIL-'+bad.length:'ACCEPT-OK')+' '+location.pathname;
    // &chain=cost,osaka,japan,quiz：POST 完跳到下一页（主屏幕网页 App 里一次点开就把五页跑完）
    const chain=(location.search.match(/[&?]chain=([^&]*)/)||[])[1]; const go=()=>{ if(!chain) return; const [nxt,...rest]=chain.split(',').filter(Boolean); if(!nxt) return; setTimeout(()=>{ location.href=(window.HIG&&HIG.ROOT||'/')+(nxt==='index'?'':nxt+'/')+'index.html?accept=1&quiet=1'+(rest.length?'&chain='+rest.join(','):''); }, 2500); };
    try{ fetch(location.origin+'/accept', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({page: location.pathname, trace: window.__sheetTrace, ua: navigator.userAgent, w: W, h: H, root, standalone: !!navigator.standalone||matchMedia('(display-mode: standalone)').matches, env: {clientH: document.documentElement.clientHeight, vvH: visualViewport&&visualViewport.height, vvTop: visualViewport&&visualViewport.offsetTop, screenH: screen.height, safeTop: safe, barPadTop: q('.bar')&&cs(q('.bar')).paddingTop, barTop: q('.bar')&&rect(q('.bar')).top, btnTop: qa('.bar .btn-glass')[0]&&rect(qa('.bar .btn-glass')[0]).top, sheetTop: q('.sheet')&&rect(q('.sheet')).top, sheetH: q('.sheet')&&rect(q('.sheet')).height, scrollY: window.scrollY, bodyH: document.body.getBoundingClientRect().height, bodyTop: document.body.getBoundingClientRect().top, htmlH: document.documentElement.getBoundingClientRect().height, efp930: (e=>e&&(e.id||e.className||e.tagName))(document.elementFromPoint(220,930)), sheetBottom: q('.sheet')&&rect(q('.sheet')).bottom, dvh: (()=>{const p=document.createElement('div'); p.style.cssText='position:fixed;top:0;height:100dvh;width:0'; document.body.appendChild(p); const v=rect(p).height; p.remove(); return v;})()}, results: res})}).then(go,go); }catch(e){ go(); }
    console.log('ACCEPT', JSON.stringify(res));
  }
  // 真机轨迹：load 后 600ms 合成一次「上推 120、停住、松手」，逐帧记 SHEET.top()（等价于对地图 App 录像逐帧量）
  window.addEventListener('load', ()=>setTimeout(()=>{ if(!(window.SHEET&&SHEET.sim)||window.innerWidth>=900) return; const T=SHEET.tops(); if(!T.medium) return; const S=SHEET.sim, tr=window.__sheetTrace=[]; const cur0=SHEET.get(); S.place(T.medium);
    const t0=performance.now(); S.begin(600,t0,false,false); S.move(480,t0+80); setTimeout(()=>{ const tr0=performance.now(); S.move(480,tr0); const d=S.end(tr0); const target=SHEET.tops()[d];
      const tick=()=>{ const t=(performance.now()-tr0)/1000; tr.push({phase:'settle', t, ta:SHEET.elapsed(), top:SHEET.top(), target}); if(t<0.8) requestAnimationFrame(tick); else { S.place(T[cur0]); SHEET.set(cur0); } }; requestAnimationFrame(tick); }, 200); }, 600));
  window.HIG_ACCEPT=show;
  window.addEventListener('load', ()=>setTimeout(show, 2500));
  // 再点一下屏幕就重量一次（网页 App 冷启动后视口会变）
  window.addEventListener('touchend', ()=>{ if(!window.__accSynthetic) setTimeout(show, 400); }, {passive:true});   // 探针自己合成的触摸不算
})();
