/* HIG 验收（在目标浏览器里量 DOM）。页面地址加 ?accept 即加载（再加 &quiet 不画覆盖层，只 POST）：把关键控件的实测尺寸和 DESIGN-HIG.md 的数字表比，
   左上角盖一块结果，并 POST 到本地 rangeserver 的 /accept（pipeline/ui/accept.py 收集）。
   只在 Safari/iOS 上的数字才算数：桌面 Chromium 没有 -apple-system-body，根字号是 16 而不是 17。 */
(function(){
  if(!/[?&]accept/.test(location.search)) return;
  const R=[]; const num=v=>Math.round(v*100)/100;
  const ok=(name, got, want, tol, note)=>{ const pass = typeof want==='number' ? Math.abs(got-want)<=tol : got===want; R.push({name, got: typeof got==='number'?num(got):got, want, pass, note}); };
  const rect=el=>el.getBoundingClientRect(); const cs=(el,ps)=>getComputedStyle(el,ps||null); const px=v=>parseFloat(v)||0;
  const q=s=>document.querySelector(s); const qa=s=>[...document.querySelectorAll(s)].filter(e=>rect(e).width>0);
  const safeNow=()=>{ const p=document.createElement('div'); p.style.cssText='position:fixed;top:0;left:0;width:0;height:0;padding-top:env(safe-area-inset-top)'; document.body.appendChild(p); const v=px(cs(p).paddingTop); p.remove(); return v; };
  // 主屏幕网页 App（黑色半透明状态栏）里 innerHeight 不含状态栏、client 坐标整体偏 +安全区；用 visualViewport 校正：屏幕 y = client y + OY
  // 网页 App 冷启动后视口会在一两秒内从 894 变成 956（状态栏半透明生效），所以这些都在量的时候现算，不在脚本加载时算
  const VV=window.visualViewport; let W,H,OY,wide,MAC,safe,root,INSET;
  function run(){
    W=window.innerWidth; H=VV?VV.height:window.innerHeight; OY=0; /* 全站已不用 position:fixed，rect 就是屏幕坐标；visualViewport.offsetTop 在网页 App 里是 -安全区，只影响 fixed 元素 */ wide=W>=900; MAC=wide&&matchMedia('(pointer: fine)').matches; safe=safeNow(); root=px(cs(document.documentElement).fontSize); INSET=W>=414?20:16;
    R.length=0;
    ok(MAC?'根字号 = 13（macOS 系统字号）':'根字号 = 17（-apple-system-body）', root, MAC?13:17, 0.01, MAC?'':'Chromium 会是 16');
    const fam=cs(document.body).fontFamily; ok('字体栈含 PingFang SC', /PingFang SC/.test(fam), true, 0, fam.split(',').slice(0,4).join(','));
    const tint=cs(document.documentElement).getPropertyValue('--tint').trim(); ok('tint', tint.toLowerCase(), matchMedia('(prefers-color-scheme: dark)').matches?'#0a84ff':'#0088ff', 0);
    // 顶部工具条：44 圆钮，左 16，贴安全区顶
    const bar=q('.bar'); if(bar){ const b=qa('.bar .btn-glass')[0]; if(b){ const r=rect(b); ok(MAC?'工具条按钮高 36':'工具条按钮高 44', r.height, MAC?36:44, 0.5); ok(MAC?'工具条按钮宽 ≥36':'工具条按钮宽 ≥44', r.width>=(MAC?35.5:43.5), true, 0, num(r.width)); if(wide){ const rb=Math.max(...qa('.bar > *').filter(b=>!b.classList.contains('spacer')).map(b=>rect(b).right)); ok(MAC?'工具条靠右 8（macOS 地图 App 控件簇）':'工具条靠右 24（iPad 地图 App 控件簇）', W-rb, MAC?8:24, 0.5); ok('工具条顶 = 安全区 + 8', Math.min(...qa('.bar .btn-glass').map(b=>rect(b).top)), safe+8, 0.5); ok(MAC?'工具条圆钮 36':'工具条圆钮 44', r.height, MAC?36:44, 0.5); } else { ok('工具条左内缩 = 布局边距 '+INSET, r.left, INSET, 0.5); ok('工具条按钮顶 = 安全区', r.top+OY, safe, 0.5, 'safe-top '+num(safe)); } } }
    // Sheet
    const sh=q('.sheet'); if(sh){ const r=rect(sh); const d=sh.dataset.detent||'medium';
      if(!wide){ ok('Sheet 左内缩 8', r.left, 8, 0.5); ok('Sheet 右内缩 8', W-r.right, 8, 0.5); ok('Sheet 圆角 38', px(cs(sh).borderTopLeftRadius), 38, 0.5);
        if(d==='medium') ok('Sheet 中档 = 44% 屏', 100*r.height/H, 44, 1); else if(d==='large') ok('Sheet 大档 = 屏高 − 62', H-r.height, 62, 1); else ok('Sheet 小档 = 96 + 安全区底', r.height, 96+0, 40, '档位 small');
        const g=q('.sheet .grab i'); if(g){ const gr=rect(g); ok('抓手 58×4', gr.width===58&&Math.abs(gr.height-4)<0.5, true, 0, num(gr.width)+'×'+num(gr.height)); ok('抓手距顶 5', gr.top-r.top, 5, 0.5); ok('抓手居中', Math.abs((gr.left+gr.right)/2-(r.left+r.right)/2), 0, 1); }
      } else if(MAC){ const panel=sh.classList.contains('panel-wide'); ok(panel?'面板宽 282（macOS 地图 App 地点卡片）':'侧栏宽 200（macOS 地图 App）', r.width, panel?282:200, 0.5); ok('侧栏左 8', r.left, 8, 0.5); ok('侧栏顶 8', r.top, safe+8, 0.5); ok('侧栏底 8', H-r.bottom, 8, 0.5); ok('侧栏圆角 14', px(cs(sh).borderTopLeftRadius), 14, 0.5); const cp=q('.sheet.split #card'); if(cp&&!cp.hidden){ const cr=rect(cp); ok('地点卡片面板 282 宽、贴侧栏右 8', Math.abs(cr.width-282)<0.5&&Math.abs(cr.left-r.right-8)<0.5, true, 0, num(cr.width)+' left+'+num(cr.left-r.right)); }
      } else { ok('侧栏宽 440（iPad 地图 App）', r.width, 440, 0.5); ok('侧栏左 24', r.left, 24, 0.5); ok('侧栏顶 = 安全区 + 8', r.top, safe+8, 0.5); ok('侧栏底 20', H-r.bottom, 20, 0.5); ok('侧栏圆角 38', px(cs(sh).borderTopLeftRadius), 38, 0.5); }
      const s=qa('.sheet .search')[0]; if(s){ const sr=rect(s); ok(MAC?'搜索框高 36':'搜索胶囊高 44', sr.height, MAC?36:44, 0.5); ok(MAC?'搜索框距面板边 15':'搜索胶囊距 Sheet 内边 16', sr.left-r.left, MAC?15:16, 0.5); ok(MAC?'搜索框距面板顶 12':(wide?'搜索胶囊距面板顶 16':'搜索胶囊距 Sheet 顶 15'), sr.top-r.top, MAC?12:(wide?16:15), 0.5); ok('搜索胶囊左内边 11', px(cs(s).paddingLeft), 11, 0.1); }
      const head=qa('.sheet .head')[0]; if(head&&!MAC){ const hb=qa('.sheet .head .btn-glass')[0]; if(hb){ const br=rect(hb); ok('卡片头圆钮 44', br.width===44&&br.height===44, true, 0, num(br.width)+'×'+num(br.height)); ok(wide?'卡片头圆钮距面板顶 16':'卡片头圆钮距 Sheet 顶 15', br.top-r.top, wide?16:15, 0.5); ok('卡片头圆钮距 Sheet 边 15', Math.min(br.left-r.left, r.right-br.right), 15, 0.5); }
        const tt=qa('.sheet .head .tt .t-title2')[0]; if(tt){ const c=cs(tt); ok('卡片头标题 22/28 粗', Math.abs(px(c.fontSize)-root*22/17)<0.2&&+c.fontWeight>=700, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))+' w'+c.fontWeight); ok('卡片头标题居中', c.textAlign, 'center', 0); ok(wide?'卡片头标题距面板顶 16':'卡片头标题距 Sheet 顶 15', rect(tt).top-r.top, wide?16:15, 0.5); }
        const st=qa('.sheet .head .tt .t-sub')[0]; if(st){ const c=cs(st); ok('卡片头副标题 15/20', Math.abs(px(c.fontSize)-root*15/17)<0.2, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))); ok('卡片头副标题单行', rect(st).height, root*20/17, 0.5); }
        const body=qa('.sheet .body')[0]; if(body&&tt){ ok('正文距标题块 16', rect(body).top-rect(head).bottom+px(cs(head).paddingBottom), 16, 0.5); } }
    }
    // 分组列表
    const g=qa('.group')[0]; if(g){ ok('卡片圆角 26', px(cs(g).borderTopLeftRadius), 26, 0.5); const gr=rect(g); const host=sh&&sh.contains(g)?rect(sh):(g.closest('main')?rect(g.closest('main')):{left:0,right:W}); ok('卡片内缩 = 布局边距 '+INSET, gr.left-host.left, INSET, 0.5); }
    const single=qa('.row').find(r=>!r.querySelector('.hint,.seg,input[type=range]')&&!r.classList.contains('slider')); if(single){ const rr=rect(single); ok('单行 52.33（Row Regular 52 + 分隔线）', rr.height, 52.33, 0.5, single.textContent.trim().slice(0,12)); ok('行左内缩 '+(single.classList.contains('icon')?'18（有图标）':'20'), px(cs(single).paddingLeft), single.classList.contains('icon')?18:20, 0.1); ok('行右内缩 20', px(cs(single).paddingRight), 20, 0.1);
      const nx=single.nextElementSibling; if(nx&&nx.classList.contains('row')){ const sp=cs(nx,'::before'); ok('分隔线内缩 '+(nx.classList.contains('icon')?60:20), px(sp.left), nx.classList.contains('icon')?60:20, 0.1); ok('分隔线 0.67 粗', Math.abs(px(sp.height)*parseFloat((sp.transform.match(/matrix\(([^)]+)\)/)||['','1,0,0,1'])[1].split(',')[3])-0.67)<0.05, true, 0, sp.height+' '+sp.transform); } }
    const two=qa('.row').find(r=>r.querySelector('.hint')); if(two){ const rr=rect(two); ok('双行 68.33（Row Tall 68 + 分隔线）', rr.height, 68.33, 0.5, two.textContent.trim().slice(0,12)); }
    const ico=qa('.row .ico')[0]; if(ico){ const ir=rect(ico); const rw=rect(ico.closest('.row')); ok('行图标 28', ir.width===28&&ir.height===28, true, 0, num(ir.width)+'×'+num(ir.height)); ok('行图标距卡片边 18', ir.left-rw.left, 18, 0.1); ok('行文字起点 60', rect(ico.closest('.row').querySelector('.lab')).left-rw.left, 60, 0.5); }
    const nm=qa('.row .name')[0]; if(nm){ ok('行文字 17/22', px(cs(nm).fontSize)===root && Math.abs(px(cs(nm).lineHeight)-root*22/17)<0.3, true, 0, px(cs(nm).fontSize)+'/'+num(px(cs(nm).lineHeight))); }
    const h2=qa('.sect h2')[0]; if(h2){ const c=cs(h2); ok('段头 17 半粗', px(c.fontSize)===root&&+c.fontWeight>=600, true, 0, px(c.fontSize)+' w'+c.fontWeight); ok('段头下距 6', px(c.paddingBottom), 6, 0.1); const nxt=h2.nextElementSibling; if(nxt) ok('段头→卡片 6', rect(nxt).top-rect(h2).bottom, 0, 0.5, '内边距已含'); const sec=h2.parentElement; const isFirst=sec===sec.parentElement.firstElementChild; ok(isFirst?'首段头上距 10':'段头上距 28', px(c.paddingTop), isFirst?10:28, 0.1); const inSheet=!!(sh&&sh.contains(h2)); ok(inSheet?'段头内缩 = 布局边距（地图 App 卡片：与卡片对齐）':'段头文字内缩 = 布局边距 + 20（设置 App）', px(c.paddingLeft), inSheet?INSET:INSET+20, 0.1); ok('段头颜色 = '+(inSheet?'label（地图 App）':'secondaryLabel（设置 App）'), c.color, inSheet?cs(document.body).color:c.color, 0); }
    const ft=qa('.sect .foot').find(f=>f.previousElementSibling&&f.previousElementSibling.classList.contains('group')); if(ft){ const c=cs(ft); ok('段尾 13/18', Math.abs(px(c.fontSize)-root*13/17)<0.2&&Math.abs(px(c.lineHeight)-root*18/17)<0.3, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))); ok('段尾上 6 下 24', px(c.paddingTop)===6&&px(c.paddingBottom)===24, true, 0, c.paddingTop+' '+c.paddingBottom); }
    const gg=qa('.group + .group')[0]; if(gg){ ok('卡片间 35', px(cs(gg).marginTop), 35, 0.1); }
    if(MAC){ // macOS 27 地图 App 实测（窗口 1280×744，AX 坐标）
      const mh=qa('.sheet .mh')[0]; if(mh){ const c=cs(mh); const inCard=!!mh.closest('#card,.panel-wide'); ok(inCard?'段头 15 半粗（地点卡片）':'侧栏段头 11 灰', px(c.fontSize), inCard?15:11, 0.1, 'w'+c.fontWeight); }
      const mr=qa('.sheet .mrow')[0]; if(mr){ const inPanel=!!mr.closest('#card,.panel-wide'); ok(inPanel?'地点卡片列表行 44':'侧栏行 32', rect(mr).height, inPanel?44:32, 0.5); const ic=mr.querySelector('.ico'); if(ic&&!inPanel) ok('侧栏行图标 22', rect(ic).width, 22, 0.5); ok('侧栏行文字 13', px(cs(mr.querySelector('.name')||mr).fontSize), 13, 0.1); }
      const mc=qa('.sheet .mcard')[0]; if(mc){ ok('地点卡片圆角 12', px(cs(mc).borderTopLeftRadius), 12, 0.5); const host=rect(mc.closest('#card')||sh); ok('地点卡片距面板边 16', rect(mc).left-host.left, 16, 0.5); const rr=qa('.sheet .mcard .r').find(x=>!x.querySelector('.hint,.seg,input[type=range],.chip')&&!x.classList.contains('slider')); if(rr){ ok('地点卡片行 44', rect(rr).height, 44, 0.5); ok('地点卡片行文字 13', px(cs(rr).fontSize), 13, 0.1); } }
      const pb=qa('.sheet .mbtn .btn.l')[0]; if(pb){ ok('主按钮 45 高距边 16', Math.abs(rect(pb).height-45)<0.5&&Math.abs(rect(pb).left-rect(pb.closest('#card')||sh).left-16)<0.5, true, 0, num(rect(pb).height)); }
      const hb=qa('.sheet .head .btn-glass')[0]; if(hb){ ok('卡片头圆钮 28 距边 12 距顶 12', Math.abs(rect(hb).width-28)<0.5&&Math.abs(rect(hb.closest('.head')).top-rect(hb).top+12)<0.6, true, 0, num(rect(hb).width)+' top+'+num(rect(hb).top-rect(hb.closest('.head')).top)); }
      const tt=qa('.sheet .head .tt .t-title2')[0]; if(tt){ ok('卡片头标题 17 粗居中', px(cs(tt).fontSize)===17&&cs(tt).textAlign==='center', true, 0, px(cs(tt).fontSize)); const st=qa('.sheet .head .tt .t-sub')[0]; if(st) ok('卡片头副标题 11', px(cs(st).fontSize), 11, 0.1); }
      const tl2=qa('.tiles button')[0]; if(tl2){ ok('地图模式磁贴 70（macOS 面板）', rect(tl2.querySelector('.img')).width, 70, 0.5); }
      const sw=qa('.sw')[0]; if(sw){ const r=rect(sw); ok('开关 38×22（NSSwitch）', r.width===38&&r.height===22, true, 0, num(r.width)+'×'+num(r.height)); }
      const seg=qa('.seg').find(x=>!x.closest('.bar')); if(seg){ ok('分段控件 24（macOS）', rect(seg).height, 24, 0.5); }
      const bseg=qa('.bar .seg')[0]; if(bseg) ok('工具条分段控件 36', rect(bseg).height, 36, 0.5);
    }
    if(!MAC){
    // 地图 App 的 Sheet 内容组件（DESIGN-HIG.md「地图 App 组件」）
    const mh=qa('.mh')[0]; if(mh){ const c=cs(mh); const host=sh&&sh.contains(mh)?rect(sh):{left:0}; ok('地图段头 17 半粗 label 色', px(c.fontSize)===root&&+c.fontWeight>=600&&c.color===cs(document.body).color, true, 0, px(c.fontSize)+' w'+c.fontWeight+' '+c.color); ok('地图段头距 Sheet 边 = 布局边距', px(c.paddingLeft), INSET, 0.1); ok('地图段头下距 10', px(c.paddingBottom), 10, 0.1); if(mh!==mh.parentElement.firstElementChild) ok('地图段头上距 28', px(c.paddingTop), 28, 0.1); }
    const mc=qa('.mcard')[0]; if(mc){ const r=rect(mc); const host=sh&&sh.contains(mc)?rect(sh):{left:0}; ok('地图卡片圆角 20', px(cs(mc).borderTopLeftRadius), 20, 0.5); ok('地图卡片距 Sheet 边 = 布局边距', r.left-host.left, INSET, 0.5); ok('地图卡片半透明填充', cs(mc).backgroundColor!=='rgba(0, 0, 0, 0)', true, 0, cs(mc).backgroundColor);
      const rr=qa('.mcard .r').find(x=>!x.querySelector('.hint,.seg,input[type=range],.chip')&&!x.classList.contains('slider')); if(rr){ ok(MAC?'地图卡片行 44（macOS）':'地图卡片行 47（17/22 + 12.5×2）', rect(rr).height, MAC?44:47, 0.5, rr.textContent.trim().slice(0,10)); ok('地图卡片行左右内边 16', px(cs(rr).paddingLeft)===16&&px(cs(rr).paddingRight)===16, true, 0, cs(rr).padding); const nx=rr.nextElementSibling; if(nx&&nx.classList.contains('r')){ const sp=cs(nx,'::before'); ok('地图卡片分隔线 1 内缩 16', px(sp.height)===1&&px(sp.left)===16, true, 0, sp.height+' '+sp.left); } } }
    const ml=qa('.mlist')[0]; if(ml){ const r=rect(ml); const host=sh&&sh.contains(ml)?rect(sh):{left:0}; ok('地图列表卡片圆角 26', px(cs(ml).borderTopLeftRadius), 26, 0.5); ok('地图列表距 Sheet 边 = 布局边距', r.left-host.left, INSET, 0.5);
      const mr=qa('.mrow').find(x=>x.querySelector('.hint')); if(mr){ ok('地图列表行 69（13.5 + 17/22 + 15/20 + 13.5）', rect(mr).height, 69, 0.5, mr.textContent.trim().slice(0,10)); const ic=mr.querySelector('.ico'); if(ic){ const ir=rect(ic); ok('地图列表圆图标 34', ir.width===34&&ir.height===34, true, 0, num(ir.width)+'×'+num(ir.height)); ok('地图列表圆图标距卡片边 16', ir.left-rect(mr).left, 16, 0.1); ok('地图列表文字起点 61', rect(mr.querySelector('.lab')).left-rect(mr).left, 61, 0.5); } const nx=mr.nextElementSibling; if(nx&&nx.classList.contains('mrow')){ const sp=cs(nx,'::before'); ok('地图列表分隔线 1 内缩 61/16', px(sp.height)===1&&px(sp.left)===61&&px(sp.right)===16, true, 0, sp.height+' '+sp.left+' '+sp.right); } } }
    const ch=qa('.chips button')[0]; if(ch){ const inSheet=sh&&sh.contains(ch); ok(MAC&&inSheet?'筛选胶囊 25（macOS）':'筛选胶囊 32', rect(ch).height, MAC&&inSheet?25:32, 0.5); ok(MAC&&inSheet?'筛选胶囊间距 9':'筛选胶囊间距 8', px(cs(ch.parentElement).columnGap||cs(ch.parentElement).gap), MAC&&inSheet?9:8, 0.1); const on=qa('.chips button[aria-pressed="true"]')[0]; if(on) ok('选中胶囊 tint 白字', cs(on).color==='rgb(255, 255, 255)', true, 0, cs(on).backgroundColor); }
    const tl2=qa('.tiles button')[0]; if(tl2){ const im=tl2.querySelector('.img'); ok('地图模式缩略块 91（87 + 2 描边）', rect(im).width===91&&rect(im).height===91, true, 0, num(rect(im).width)+'×'+num(rect(im).height)); ok('缩略块间距 10', px(cs(tl2.parentElement).columnGap||cs(tl2.parentElement).gap), 10, 0.1); const lb=tl2.querySelector('.lb'); ok('缩略块标签 13 距块 10', Math.abs(px(cs(lb).fontSize)-root*13/17)<0.2&&px(cs(lb).marginTop)===10, true, 0, num(px(cs(lb).fontSize))+' mt'+cs(lb).marginTop); }
    const sg=qa('.sugg')[0]; if(sg){ ok('建议卡圆角 16', px(cs(sg).borderTopLeftRadius), 16, 0.5); const ic=sg.querySelector('.ico'); if(ic) ok('建议卡圆图标 36', rect(ic).width, 36, 0.5); ok('建议卡标题 17 半粗', +cs(sg.querySelector('.t')).fontWeight>=600&&px(cs(sg.querySelector('.t')).fontSize)===root, true, 0); }
    const pb=qa('.mbtn .btn.l')[0]; if(pb){ const r=rect(pb); const host=sh&&sh.contains(pb)?rect(sh):{left:0,right:W}; ok('地图主按钮 50 高距 Sheet 边 20', Math.abs(r.height-50)<0.5&&Math.abs(r.left-host.left-20)<0.5, true, 0, num(r.height)+' left+'+num(r.left-host.left)); }
    // 控件
    const seg=qa('.seg').find(x=>!x.closest('.bar')); if(seg){ const c=cs(seg); ok('分段控件高 '+(seg.classList.contains('l')?50:32), rect(seg).height, seg.classList.contains('l')?50:32, 0.5); ok('分段内边 2 段间 4', px(c.paddingTop)===2&&px(c.columnGap||c.gap)===4, true, 0, c.padding+' gap '+(c.columnGap||c.gap)); const on=seg.querySelector('[aria-pressed="true"]'); if(on) ok('选中段白底', cs(on).backgroundColor!=='rgba(0, 0, 0, 0)', true, 0, cs(on).backgroundColor); }
    const bs={s:28,m:34,l:50}; for(const k in bs){ const b=qa('.btn.'+k)[0]; if(b) ok('按钮 '+k.toUpperCase()+' 高 '+bs[k], rect(b).height, bs[k], 0.5); }
    const bseg=qa('.bar .seg')[0]; if(bseg) ok('工具条分段控件 44（与圆钮同高；Kit 待核）', rect(bseg).height, 44, 0.5);
    const sw=qa('.sw')[0]; if(sw){ const r=rect(sw); ok('开关 63×28', r.width===63&&r.height===28, true, 0, num(r.width)+'×'+num(r.height)); const k=cs(sw.querySelector('i'),'::after'); ok('开关圆钮 38×24', px(k.width)===38&&px(k.height)===24, true, 0, k.width+'×'+k.height); }
    const sl=qa('.row.slider input[type=range]')[0]; if(sl) ok('滑块热区 28', rect(sl).height, 28, 0.5);
    }
    const mn=q('.menu'); if(mn){ const was=mn.hidden; mn.hidden=false; const mb=mn.querySelector('button'); ok('下拉菜单 248 宽 圆角 26（UIMenu）', Math.abs(rect(mn).width-248)<0.5&&px(cs(mn).borderTopLeftRadius)===26, true, 0, num(rect(mn).width)+' r'+cs(mn).borderTopLeftRadius); if(mb) ok('菜单行 42 标签距左 50', Math.abs(rect(mb).height-42)<0.5&&px(cs(mb).paddingLeft)===50, true, 0, num(rect(mb).height)+' pl'+cs(mb).paddingLeft); ok('菜单上下内边 5', px(cs(mn).paddingTop)===5&&px(cs(mn).paddingBottom)===5, true, 0, cs(mn).padding); mn.hidden=was; }
    const tl=qa('.t-large')[0]; if(tl){ const c=cs(tl); ok('大标题 34/41 700', Math.abs(px(c.fontSize)-root*2)<0.2&&+c.fontWeight>=700, true, 0, num(px(c.fontSize))+'/'+num(px(c.lineHeight))+' w'+c.fontWeight); }
    const sfx=qa('.sf')[0]; if(sfx){ const m=cs(sfx).maskImage||cs(sfx).webkitMaskImage; ok('SF Symbols 蒙版已装', /ui\/sf\/.+\.png/.test(m), true, 0, (m||'').slice(0,60)); }
    const mv=cs(document.documentElement).getPropertyValue('--ease').trim(); if(matchMedia('(prefers-reduced-motion: reduce)').matches) ok('减弱动态：过渡关闭', cs(sh||document.body).transitionDuration, '0s', 0);
    // 深色
    const dark=matchMedia('(prefers-color-scheme: dark)').matches; ok('配色 = 系统'+(dark?'深':'浅')+'色', cs(document.body).backgroundColor, dark?'rgb(0, 0, 0)':(sh?cs(document.body).backgroundColor:'rgb(242, 242, 247)'), 0);
    return R;
  }
  function show(){
    const res=run(); const bad=res.filter(r=>!r.pass);
    if(!/[?&]quiet/.test(location.search)){
    let box=q('#accept'); if(!box){ box=document.createElement('pre'); box.id='accept'; box.style.cssText='position:fixed;top:0;left:0;z-index:9999;margin:0;max-height:100dvh;overflow:auto;font:11px/1.45 ui-monospace,Menlo,monospace;background:rgba(255,255,255,.94);color:#000;padding:calc(env(safe-area-inset-top) + 6px) 8px 8px;max-width:100%;white-space:pre-wrap'; document.body.appendChild(box); }
    box.textContent=`${location.pathname}  ${W}×${H}${navigator.standalone?' 网页App':''}  ${bad.length?'✗ '+bad.length+' 项超差':'✓ 全部通过'}  (${res.length} 项)\n`+res.map(r=>`${r.pass?'✓':'✗'} ${r.name}: ${r.got}${r.want!==undefined&&!r.pass?'  期望 '+r.want:''}${r.note?'  ['+r.note+']':''}`).join('\n');
    }
    document.title=(bad.length?'ACCEPT-FAIL-'+bad.length:'ACCEPT-OK')+' '+location.pathname;
    // &chain=cost,osaka,japan,quiz：POST 完跳到下一页（主屏幕网页 App 里一次点开就把五页跑完）
    const chain=(location.search.match(/[&?]chain=([^&]*)/)||[])[1]; const go=()=>{ if(!chain) return; const [nxt,...rest]=chain.split(',').filter(Boolean); if(!nxt) return; setTimeout(()=>{ location.href=(window.HIG&&HIG.ROOT||'/')+(nxt==='index'?'':nxt+'/')+'index.html?accept=1&quiet=1'+(rest.length?'&chain='+rest.join(','):''); }, 2500); };
    try{ fetch(location.origin+'/accept', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({page: location.pathname, ua: navigator.userAgent, w: W, h: H, root, standalone: !!navigator.standalone||matchMedia('(display-mode: standalone)').matches, env: {clientH: document.documentElement.clientHeight, vvH: visualViewport&&visualViewport.height, vvTop: visualViewport&&visualViewport.offsetTop, screenH: screen.height, safeTop: safe, barPadTop: q('.bar')&&cs(q('.bar')).paddingTop, barTop: q('.bar')&&rect(q('.bar')).top, btnTop: qa('.bar .btn-glass')[0]&&rect(qa('.bar .btn-glass')[0]).top, sheetTop: q('.sheet')&&rect(q('.sheet')).top, sheetH: q('.sheet')&&rect(q('.sheet')).height, scrollY: window.scrollY, bodyH: document.body.getBoundingClientRect().height, bodyTop: document.body.getBoundingClientRect().top, htmlH: document.documentElement.getBoundingClientRect().height, efp930: (e=>e&&(e.id||e.className||e.tagName))(document.elementFromPoint(220,930)), sheetBottom: q('.sheet')&&rect(q('.sheet')).bottom, dvh: (()=>{const p=document.createElement('div'); p.style.cssText='position:fixed;top:0;height:100dvh;width:0'; document.body.appendChild(p); const v=rect(p).height; p.remove(); return v;})()}, results: res})}).then(go,go); }catch(e){ go(); }
    console.log('ACCEPT', JSON.stringify(res));
  }
  window.HIG_ACCEPT=show;
  window.addEventListener('load', ()=>setTimeout(show, 2500));
  // 再点一下屏幕就重量一次（网页 App 冷启动后视口会变）
  window.addEventListener('touchend', ()=>setTimeout(show, 400), {passive:true});
})();
